import { PricingTier, SubscriptionPlanType } from '../types';

export const USD_PRICING_TIERS: Record<SubscriptionPlanType, PricingTier> = {
  free: {
    id: 'free',
    planKey: 'free',
    name: 'Free Tier',
    badge: 'Standard',
    priceUsd: 0,
    periodLabel: '$0 / forever',
    billingPeriod: 'free',
    aiGenerationsLimit: 3,
    ctaText: 'Current Plan',
    features: [
      '3 AI Generations per day',
      'Basic Lecture Summaries',
      'Interactive Practice Quizzes',
      'Standard Timetable Matrix',
      'Community Support',
    ],
  },
  pro_weekly: {
    id: 'pro_weekly',
    planKey: 'pro_weekly',
    name: 'Pro Weekly',
    badge: 'Flexible',
    priceUsd: 0.99,
    periodLabel: '$0.99 / week',
    billingPeriod: 'weekly',
    durationDays: 7,
    aiGenerationsLimit: Infinity,
    ctaText: 'Subscribe for $0.99/wk',
    features: [
      'Unlimited AI Generations',
      'Full Lecture Video Summarizer',
      'High-Speed Flash Model (Gemini 3.1)',
      'Export to Flashcards & Markdown',
      'Unlimited Practice Quizzes with Explanations',
      'Priority Server Queue',
      'Cancel anytime',
    ],
  },
  pro_monthly: {
    id: 'pro_monthly',
    planKey: 'pro_monthly',
    name: 'Pro Monthly',
    badge: 'Most Popular',
    priceUsd: 2.99,
    periodLabel: '$2.99 / month',
    billingPeriod: 'monthly',
    durationDays: 30,
    isPopular: true,
    aiGenerationsLimit: Infinity,
    ctaText: 'Subscribe for $2.99/mo',
    features: [
      'Unlimited AI Generations',
      'All Pro Weekly Features Included',
      'Interactive Analytics & Study Trends',
      'Audio Lecture Notes & TTS Playback',
      'Full Timetable Auto-Scheduler',
      'Custom Video Player with Smart Notes',
      '24/7 Priority Support',
    ],
  },
  pro_yearly: {
    id: 'pro_yearly',
    planKey: 'pro_yearly',
    name: 'Pro Yearly',
    badge: 'Best Value (Save 30%)',
    priceUsd: 24.99,
    periodLabel: '$24.99 / year',
    billingPeriod: 'yearly',
    durationDays: 365,
    isBestValue: true,
    aiGenerationsLimit: Infinity,
    ctaText: 'Subscribe for $24.99/yr',
    features: [
      'Everything in Pro Monthly',
      'Save over 30% ($2.08/mo effective)',
      'Full Offline PWA Sync Access',
      'Early Access to New AI Models',
      'Custom Subject Syllabus Analysis',
      'Direct Academic Tutor Mode',
      'VIP Support & Feature Requests',
    ],
  },
};

export const PRICING_LIST: PricingTier[] = [
  USD_PRICING_TIERS.free,
  USD_PRICING_TIERS.pro_weekly,
  USD_PRICING_TIERS.pro_monthly,
  USD_PRICING_TIERS.pro_yearly,
];

export const PAID_PLANS: PricingTier[] = [
  USD_PRICING_TIERS.pro_weekly,
  USD_PRICING_TIERS.pro_monthly,
  USD_PRICING_TIERS.pro_yearly,
];
